[phases.build]
cmds = [
    '''go get github.com/gopher-fleece/gleece''',
    '''go install github.com/gopher-fleece/gleece''',
    '''gleece''',
    '''GOOS=linux GOARCH=amd64 go build -ldflags='-s' -o=./bin/linux_amd64/api ./cmd/api'''
]

[start]
cmd = './bin/linux_amd64/api'